### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by dimamo5** [sergio-domingues/SINF_Sales-Force-Automation#61]

**Comment by tomislaaaav** [comment]
yeah we really need a readme file boys, i can't understand shit of this project

**Comment by tomislaaaav** [comment]
i see you @IneSantos, you're assigned to this and you're playing league of legends

**Comment by dimamo5** [comment]
^ True @IneSantos do the ******* readme plz :D

**Comment by andrelago13** [comment]
@tomislaaaav why are you invading our excelent project?
